# -*- coding: utf-8 -*-
"""Copy of dashboard_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STKGtHS9LMzmQ9b075_1qCRwNZK_l045
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load your dataset
# Replace 'your_data.csv' with your actual data file
url = 'https://github.com/suhaodatascichem/dashboard-streamlit/raw/refs/heads/main/Soybean%20meal.xlsx'
df = pd.read_excel(url, engine="openpyxl")

df.columns

plt.scatter(df['CP'],df['NH3'])
plt.figure(figsize=(10,6))
plt.show()

# Sidebar options
st.sidebar.header("Chart Settings")
chart_type = st.sidebar.selectbox("Select Chart Type", ["Scatter Plot", "Bar Chart"])

# Column selection
numeric_columns = df.select_dtypes(include=['number']).columns.tolist()

if len(numeric_columns) < 2:
    st.error("Dataset must contain at least two numeric columns for visualization.")
else:
    x_axis = st.sidebar.selectbox("Select X-Axis", numeric_columns)
    y_axis = st.sidebar.selectbox("Select Y-Axis", numeric_columns)

    # Generate chart
    st.title("📊 Data Visualization Dashboard")

    if chart_type == "Scatter Plot":
        fig = px.scatter(df, x=x_axis, y=y_axis, title=f"Scatter Plot: {x_axis} vs {y_axis}")
        st.plotly_chart(fig, use_container_width=True)

    elif chart_type == "Bar Chart":
        fig = px.bar(df, x=x_axis, y=y_axis, title=f"Bar Chart: {x_axis} vs {y_axis}")
        st.plotly_chart(fig, use_container_width=True)

    # Show dataset preview
    with st.expander("🔍 View Dataset"):
        st.write(df.head())